### ISSUE TITLE
Attempt to specify the timezone in date format.

### ISSUE THREAD

**Issue by ShaneKent** [ShaneKent/PyEventLogViewer#109]
Originally from issue #89, failed during that sprint.

Attempt to allow users to specify their timezones.

**Comment by carterv** [comment]
@ShaneKent can I ask why this failed? The functionality was added in #103

**Comment by ShaneKent** [comment]
@carterv because I didn't have time to complete it.

**Comment by carterv** [comment]
@ShaneKent Huh, seems I wasn't paying attention to who owned it and filled out all the info for this test in the ICD, including screenshots. Are you fine if I mark this as closed?

**Comment by ShaneKent** [comment]
@carterv Fine with me.
