### ISSUE TITLE
Set up documentation framework

### ISSUE THREAD

**Issue by carterv** [ShaneKent/PyEventLogViewer#11]
Sphinx?

An alternative is to manually set up a GitHub wiki and update that. I feel that might be unreliable, and propose that we only use that for functional documentation rather than code documentation.

**Comment by ShaneKent** [comment]
I've closed this issue. I spent some time looking into Sphinx and it seems as though it would be a large amount of work in-and-of itself. I don't think this needs to have a section dedicated to it if we are set in trying to create good comments and internal documentation.
