### ISSUE TITLE
Sprint #1 - Record collection

### ISSUE THREAD

**Issue by carterv** [ShaneKent/PyEventLogViewer#13]
* Write `collect.collect_records` to collect events from an event log file. Do not include filtering.
* Write `collect.collect_deleted_records` to carve deleted events from an event log file.
* Write `collect.get_machine_name` to parse the machine name from an event log file.
* Write `collect.get_log_file_hash` to get verification info from an event log file.

**Comment by ShaneKent** [comment]
Closed with #21 merge.
