### ISSUE TITLE
Recover deleted event logs

### ISSUE THREAD

**Issue by carterv** [ShaneKent/PyEventLogViewer#23]
Pull the deleted event logs into the database.

**Comment by ShaneKent** [comment]
@carterv @SarahStephens @zjmonroe23 - this requires discussion from all hands.

I don't believe that "recovering deleted event logs" is possible. See this discussion that I'm having with the pyevtx library author: [pyevtx](https://github.com/libyal/libevtx/issues/13). I have two identical event logs where Log1 has a few hundred records and Log2 is the same log file but it has been cleared via the Windows EventViewer GUI. Log1 is about 3.2MB in size whereas Log2 is about 70KB. This immediately tells me that the "deleted logs" aren't even stored in the file itself. 

Adding to this, when I use the "get_recovered_records" function in the pyevtx file, there are 0 records that are returned. It appears as though this follows what is expected according to the author [here](https://github.com/libyal/libevtx/issues/2).

With this being said - I don't think we have any way of actually recovering these deleted events. Please let me know what you all think about this.

**Comment by carterv** [comment]
I'm okay with us not being able to meet this requirement pending a discussion with the client. I'd like to see code related to this functionality removed after that.

**Comment by ShaneKent** [comment]
Per discussion with client on 22 Jan, we will be trying to "recover" some logs with the libevtx functionality. Our client will be sending us some logs to try and parse for recoverable logs.
