### ISSUE TITLE
Expand menu

### ISSUE THREAD

**Issue by carterv** [ShaneKent/PyEventLogViewer#43]
Map existing functionality to the menu and add shortcuts. 

Currently, I can think of a few functions that should be added. 

* Import - Ctrl+I
* Exit - Ctrl + Q

I would like this issue to be a location for us to track all menu functionality that should be added.

**Comment by carterv** [comment]
* Help menu (about, license, etc)
* Open project directory
* Settings (to be implemented)

**Comment by ShaneKent** [comment]
@carterv I need your input for what to put in the licensing portion of the help menu. Once that is done we can close this issue.

**Comment by carterv** [comment]
@ShaneKent Please copy the licensing info from the LICENSE file into the menu option. If that can be handled dynamically so that changes to the license file are reflected automatically, that would be ideal. If it can't, it's not a huge issue.

Once that is done this issue can be closed out.
