### ISSUE TITLE
Review events collected

### ISSUE THREAD

**Issue by carterv** [ShaneKent/PyEventLogViewer#44]
The client asked that we review the events added in Windows 10 to determine if the list of events we are collecting needs to be modified.

**Comment by ShaneKent** [comment]
This is an interesting request. I'm not sure where we can find a useful list of the event records. I'll look into it though.

**Comment by carterv** [comment]
The client brought up that he would like to see the event associated with plugging in USB devices included. 

I thought there was a list of event ids on technet, but I can't seem to find one with a quick google search. More digging might produce something.

**Comment by ShaneKent** [comment]
See comment above. The IDs to look for are 20001 and 20003. Open the attached file in Excel to see the records that TZworks exported when asked to export USB records. @carterv 

[results.txt](https://github.com/ShaneKent/PyEventLogViewer/files/1669771/results.txt)

**Comment by carterv** [comment]
Thanks @ShaneKent. I'm moving this to blocked pending the parsing refactor. 

I can't seem to find an article on 10000 specifically (there are multiple event sources using the event id 10000, which again highlights the need to use event id and source as the identifier).
 
20001 is for driver installation: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc756336(v=ws.10)

20003 is for service installation: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd349407(v%3dws.10)
