### ISSUE TITLE
User specified timestamp offset

### ISSUE THREAD

**Issue by carterv** [ShaneKent/PyEventLogViewer#84]
- [x] Add an option to the settings which allows the user to specify a timezone. 
- [x] Display timezone options as UTC offsets.
- [x] Display region indicators along with the UTC offset.
- [x] Apply the timezone offset to the database query
- [x] Change the UI to reflect the current timezone
- [x] Make the timezone persistent (save it in the project config)

**Comment by carterv** [comment]
This issue is being placed on ice because displaying friendly names for the timezones is low-priority at this point.

**Comment by ShaneKent** [comment]
@carterv Finish this issue please.
