### ISSUE TITLE
Right click to enable/disable columns doesn't work on macOS

### ISSUE THREAD

**Issue by carterv** [ShaneKent/PyEventLogViewer#85]

**Comment by ShaneKent** [comment]
@carterv Review this: https://stackoverflow.com/questions/28197925/tkinter-mac-checkbutton-deselect-animation-glitch

**Comment by carterv** [comment]
So another issue with the version of tkinter shipped on macs? If so, feel free to close this issue after labeling as `wontfix`. 

Oddly enough, there was a different visual glitch with the checkboxes in the export GUI that was appearing on Windows, and I was unable to find a solution for that.
