### ISSUE TITLE
Set up unit testing

### ISSUE THREAD

**Issue by carterv** [ShaneKent/PyEventLogViewer#9]
We should set up a unit testing framework. Pytest might be a good one.

**Comment by zjmonroe23** [comment]
Using pytest framework

**Comment by zjmonroe23** [comment]
Some functionality implemented in pull request #78

**Comment by zjmonroe23** [comment]
TODO: Check xml string against parsed data

**Comment by carterv** [comment]
I'm of the opinion that since this issue was specifically for setting up the unit testing framework, it can be closed out. @zjmonroe23 you can make the final call on that, but I'd like to see follow-up issues created for testing various parts of the program.
