### ISSUE TITLE
Use enter key for submit

### ISSUE THREAD

**Issue by carterv** [ShaneKent/PyEventLogViewer#96]
Bind the enter key to the submit button for...
- [ ] the new project UI
- [ ] the import UI
- [ ] the timeline color UI
- [ ] the query UI

Also
- [ ] Review to ensure that all appropriate UI elements were included in the above list

**Comment by carterv** [comment]
Also bind escape where appropriate.

**Comment by ShaneKent** [comment]
@carterv What do you mean by "Review to ensure that all..."?

**Comment by carterv** [comment]
@ShaneKent double check to make sure I didn't miss any places where the enter key needs to be bound to the submit button.
